/**
 * Test user credentials.
 *
 * Admin is bootstrapped by the backend on startup.
 * All other test accounts are created by global.setup.ts via the admin API.
 * Passwords must satisfy: 8+ chars, uppercase, lowercase, digit.
 */

export const ADMIN_USER = {
  phone:    '+237690000000',          // bootstrapped phone — admin email is null in DB
  email:    'admin@smartcampost.cm',  // not usable for login (email field is null)
  password: 'Admin@SmartCAMPOST2026',
  role:     'ADMIN',
  dashboard: '/admin',
} as const;

export const TEST_CLIENT = {
  phone:    '+237699000001',
  email:    'testclient@smartcampost.test',
  fullName: 'Test Client User',
  password: 'Test123!Client',
  role:     'CLIENT',
  dashboard: '/client',
} as const;

export const TEST_STAFF = {
  phone:    '+237699000002',
  email:    'teststaff@smartcampost.test',
  fullName: 'Test Staff User',
  password: 'Test123!Staff',
  role:     'STAFF',
  dashboard: '/staff',
} as const;

export const TEST_AGENT = {
  phone:    '+237699000003',
  email:    'testagent@smartcampost.test',
  fullName: 'Test Agent User',
  password: 'Test123!Agent',
  role:     'AGENT',
  dashboard: '/agent',
} as const;

export const TEST_COURIER = {
  phone:    '+237699000004',
  email:    'testcourier@smartcampost.test',
  fullName: 'Test Courier User',
  password: 'Test123!Courier',
  role:     'COURIER',
  dashboard: '/courier',
} as const;

export const TEST_FINANCE = {
  phone:    '+237699000005',
  email:    'testfinance@smartcampost.test',
  fullName: 'Test Finance User',
  password: 'Test123!Finance',
  role:     'FINANCE',
  dashboard: '/finance',
} as const;

export const TEST_RISK = {
  phone:    '+237699000006',
  email:    'testrisk@smartcampost.test',
  fullName: 'Test Risk User',
  password: 'Test123!Risk',
  role:     'RISK',
  dashboard: '/risk',
} as const;

export const TEST_FREEZE_TARGET = {
  phone:    '+237699000099',
  email:    'freezetarget@smartcampost.test',
  fullName: 'Freeze Target User',
  password: 'Test123!Freeze',
  role:     'CLIENT',
  dashboard: '/client',
} as const;

/** Dedicated user for password reset tests — keeps TEST_CLIENT password intact */
export const TEST_RESET_USER = {
  phone:    '+237699000077',
  email:    'resetuser@smartcampost.test',
  fullName: 'Reset Test User',
  password: 'Test123!ResetOrig',
  role:     'CLIENT',
  dashboard: '/client',
} as const;

/**
 * OTP is randomly generated by the backend (SecureRandom).
 * Use SMARTCAMPOST_OTP_EXPOSE_CODE=true to get the real code in API responses.
 * Tests capture it via Playwright route interception — do not hardcode '000000'.
 */
export const MOCK_OTP = '000000'; // kept for legacy reference only

/** Auth state file paths (populated by global.setup.ts) */
export const AUTH_STATE = {
  admin:   'e2e/.auth/admin.json',
  client:  'e2e/.auth/client.json',
  staff:   'e2e/.auth/staff.json',
  agent:   'e2e/.auth/agent.json',
  courier: 'e2e/.auth/courier.json',
  finance: 'e2e/.auth/finance.json',
  risk:    'e2e/.auth/risk.json',
} as const;
