package com.smartcampost.backend.service;

import com.smartcampost.backend.dto.agency.AgencyRequest;
import com.smartcampost.backend.exception.ConflictException;
import com.smartcampost.backend.exception.ResourceNotFoundException;
import com.smartcampost.backend.model.Agency;
import com.smartcampost.backend.repository.AgencyRepository;
import com.smartcampost.backend.service.impl.AgencyServiceImpl;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class AgencyServiceImplTest {

    @Mock private AgencyRepository agencyRepository;
    @InjectMocks private AgencyServiceImpl agencyService;

    @Test
    void createAgency_withDuplicateCode_shouldThrowConflict() {
        AgencyRequest req = new AgencyRequest();
        req.setAgencyName("Test Agency");
        req.setAgencyCode("AG-001");
        when(agencyRepository.findByAgencyCode("AG-001")).thenReturn(Optional.of(new Agency()));
        assertThrows(ConflictException.class, () -> agencyService.createAgency(req));
    }

    @Test
    void createAgency_withAutoGeneratedCode_shouldSucceed() {
        AgencyRequest req = new AgencyRequest();
        req.setAgencyName("New Agency");
        when(agencyRepository.findByAgencyCode(any())).thenReturn(Optional.empty());
        Agency saved = Agency.builder().id(UUID.randomUUID()).agencyName("New Agency").agencyCode("AG-123").city("Douala").region("Littoral").country("Cameroon").build();
        when(agencyRepository.save(any())).thenReturn(saved);

        var result = agencyService.createAgency(req);
        assertNotNull(result);
        assertEquals("New Agency", result.getAgencyName());
    }

    @Test
    void getAgency_notFound_shouldThrow() {
        UUID id = UUID.randomUUID();
        when(agencyRepository.findById(id)).thenReturn(Optional.empty());
        assertThrows(ResourceNotFoundException.class, () -> agencyService.getAgency(id));
    }

    @Test
    void listAgencies_shouldReturnAll() {
        Agency a1 = Agency.builder().id(UUID.randomUUID()).agencyName("A1").agencyCode("C1").country("Cameroon").build();
        Agency a2 = Agency.builder().id(UUID.randomUUID()).agencyName("A2").agencyCode("C2").country("Cameroon").build();
        when(agencyRepository.findAll()).thenReturn(List.of(a1, a2));

        var result = agencyService.listAgencies();
        assertEquals(2, result.size());
    }

    @Test
    void deleteAgency_notFound_shouldThrow() {
        UUID id = UUID.randomUUID();
        when(agencyRepository.findById(id)).thenReturn(Optional.empty());
        assertThrows(ResourceNotFoundException.class, () -> agencyService.deleteAgency(id));
    }

    @Test
    void updateAgency_withDuplicateNewCode_shouldThrowConflict() {
        UUID id = UUID.randomUUID();
        Agency existing = Agency.builder().id(id).agencyName("Old").agencyCode("OLD-1").country("Cameroon").build();
        when(agencyRepository.findById(id)).thenReturn(Optional.of(existing));
        when(agencyRepository.findByAgencyCode("TAKEN")).thenReturn(Optional.of(new Agency()));

        AgencyRequest req = new AgencyRequest();
        req.setAgencyName("Updated");
        req.setAgencyCode("TAKEN");
        assertThrows(ConflictException.class, () -> agencyService.updateAgency(id, req));
    }
}
